### ISSUE TITLE
create .json file for labelme dataset

### ISSUE THREAD

**Issue by jsseng** [htrick/Senior-Project#14]
I realized I have a couple other datasets using another previous labelling system, Labelme.  This dataset has the data stored in .xml files.  

Create another script that takes the Labelme .xml files and generates a single .json file that is the same format as the scale.ai .json file.  Then, you can use the scale.ai parser to download the images and generate the masks.

It should run in the following manner:  ./labelme_to_scaleai.py URL

URL is currently:  http://users.csc.calpoly.edu/~jseng/scale_ai_image/labelme/dataset_hdr

**Comment by htrick** [comment]
Should I assume you have already approved all of the polygons for the LabelMe data? Also, would you like the documentation for this script included with the main README or in a separate file?

**Comment by jsseng** [comment]
Yes, assume the polygons are approved.  But, we should still look at the validation images to make sure because I believe there may be some errors.  You can include the documentation in the main README for now.
