### ISSUE TITLE
URL can't contain control characters

### ISSUE THREAD

**Issue by jsseng** [htrick/Senior-Project#18]
I ran the labeme converter script on the directory:

    python3 labelme_to_scaleai.py http://users.csc.calpoly.edu/\~jseng/scale_ai_image/labelme/dataset

This is a slightly different dataset (non-HDR images).  The labeme.json is built, but then when I run:

    python3 dataExtractor.py -a -scale labelme.json -c config

I get the error:

```  File "/usr/lib/python3.6/http/client.py", line 1135, in putrequest
    raise InvalidURL(f"URL can't contain control characters. {url!r} "
http.client.InvalidURL: URL can't contain control characters. '/~jseng/scale_ai_image/labelme/dataset/Images/\n1_20_18_44.jpg' (found at least '\n')

**Comment by htrick** [comment]
It looks like there is a problem with that specific XML file.
[http://users.csc.calpoly.edu/~jseng/scale_ai_image/labelme/dataset/Annotations/1_20_18_44.xml](http://users.csc.calpoly.edu/~jseng/scale_ai_image/labelme/dataset/Annotations/1_20_18_44.xml)
The filename tag contains whitespace and there are no polygon coordinates.

**Comment by jsseng** [comment]
Can you trim all leading/trailing whitespace from the name and add a default polygon where it draws the line all along the bottom?
