### ISSUE TITLE
handling multiple .json files

### ISSUE THREAD

**Issue by jsseng** [htrick/Senior-Project#19]
This does not seem to work:  

    python3 dataExtractor.py -a -scale tasks.json -scale labelme.json -c config

**Comment by saehejkang** [comment]
fix the argument checking and add error checking for each piece

Make usage message more clear

Required: config file

Optional: all flags, label file and scale file

**Comment by jsseng** [comment]
I get this error message:

    python3 dataExtractor.py -a -labelbox labelbox_small_export.csv -scale labelme_hdr.json -scale labelme_sdr.json -c config

  File "dataExtractor.py", line 408, in <module>
    d._main()
  File "dataExtractor.py", line 44, in _main
    self.splitImages(validPercent)
  File "dataExtractor.py", line 388, in splitImages
    numValid = round(len(images) * validPercent)
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

**Comment by saehejkang** [comment]
only way to run it is by putting the multiple files after the -scale 

python3 dataExtractor.py -a -labelbox labelbox_small_export.csv -scale labelme_hdr.json labelme_sdr.json -c config

**Comment by jsseng** [comment]
It still doesn't work.  Please try:

    python3 dataExtractor.py -a -scale labelme_hdr.json labelme_sdr.json -labelbox labelbox_small_export.csv -c config

You will get the error at the end after generating all the masks.

**Comment by saehejkang** [comment]
Could you add the files you are running scale with to the repo? I don't see them there

**Comment by jsseng** [comment]
Okay, I just added the files.

**Comment by saehejkang** [comment]
Running the program now. Got no issues so far

**Comment by saehejkang** [comment]
Ok the issue is that the -p flag is required and it is set to none because it was not given at all.

If the user user puts just "-p" the value will be set to 0.15

If the user does not put "-p" the value will be set to none.

What I will do is, if the -p flag is none, I will set it to 0.15 every time.

Do you want me to output a message if the -p flag was not set and it was automatically set to 0.15?

"-p flag was not found. Value was set to 0.15"

**Comment by jsseng** [comment]
The default behavior should be that the percentage of validation images should be 15% if -p is not specified.  The -p is used to override the default value.

**Comment by saehejkang** [comment]
Fixed it all and tested code. Pull the new code I pushed and run it one more time.
