### ISSUE TITLE
leftmost point starts at bottom of screen

### ISSUE THREAD

**Issue by jsseng** [htrick/Senior-Project#22]
For most of the images in the labelme dataset, the leftmost data point is at the bottom of the screen.  Is this from a slant on the left side of the image mask?

**Comment by jsseng** [comment]
I tried it again, but for some images (sdr dataset), the leftmost point is still in the incorrect position.  For many of them, the point is in between the bottom and the correct location.

**Comment by htrick** [comment]
I went through all images in both datasets and the mask validation looks correct. When I fixed this issue last week, I made the changes to labelme_to_scaleai.py script, so you would need to run that again to create the updated json file.

**Comment by jsseng** [comment]
Yes, I didn't re-run that and when I did, things looked okay.  One thing I did notice was that there were some similar issue with the labelbox dataset.  I went back and fixed some of the polygons, but could there be a check asserted in the dataextractor script that flags when this issue looks possible?  Then we can go double check the polygon itself.

**Comment by htrick** [comment]
I believe that was the idea with the whitelist/blacklist directories. Would you like a print statement for each potentially incorrect mask, but still save it with the rest of the images? Also, which images in the labelbox set are causing issues? I looked through the ones in the small csv file and they looked good.

**Comment by jsseng** [comment]
How about just a print statement.  I went through the small csv file and found 2 bad polygons and fixed them.

**Comment by htrick** [comment]
I found a potential fix by printing a warning if a polygon only has one point with an x coordinate of 0 or one point with an x coordinate of its width minus 1. This method flags some images that are ok, but it seems like it catches the case when there is actually an issue.

**Comment by jsseng** [comment]
I re-ran the script and am going through the images to fix the polygons.  It is a slow process, but the majority of the flagged images have a polygon error.

**Comment by htrick** [comment]
I changed it so it prints a message if the difference between the first two points is double the difference between the next two. Also, I added the optional flag "-warnings" to control this behavior. I tested it with the smaller labelme dataset (before it adjusts the polygon in labelme_to_scaleai.py) and it looks like it flags all of the images with problems.

**Comment by jsseng** [comment]
Can this check be done in dataExtractor (when generating the actual datapoints)?  Also, if double doesn't work, then try a higher threshold.  Or, just try if the absolute difference between the first and second point is bigger than some threshold.

**Comment by htrick** [comment]
I put all of this in dataExtractor. The thing in labelme_to_scaleai is what adjusts the x coordinate to 0 if it's 4 or less since most of the images from the labelme dataset had that error.

**Comment by jsseng** [comment]
The check you put in flagged another 10 or so files that were actual errors.  I will fix those polygons.
