### ISSUE TITLE
modify mobilenetV2 class to create Efficientnet with 128 outputs

### ISSUE THREAD

**Issue by jsseng** [htrick/Senior-Project#27]

**Comment by jsseng** [comment]
Finish this by next week.

**Comment by htrick** [comment]
I created this class in a new directory, but I haven't been able to run it yet because I'm having a hard time installing TensorFlow 2 on my mac.

**Comment by jsseng** [comment]
If you still have problems it might be worth creating a VM Linux image.

**Comment by jsseng** [comment]
I just tried it and there are a couple minor bugs, but once you fix them, I could load it in Tensorflow 2.
