### ISSUE TITLE
modify the inference script to handle unlabeled images

### ISSUE THREAD

**Issue by jsseng** [htrick/Senior-Project#31]
Run unlabeled images through 4 models and compute the total variance across the data points (compute the variance for each of the 80 data points and then sum across all 80 data points).  This will give a single number.  Sort the images by variance and create a .csv file that can be loaded into Excel to visualize the variance totals.

**Comment by htrick** [comment]
If you run "python inference.py -variance" it creates a file "variance.csv" that lists each image from the "Unlabeled" directory and its variance.

**Comment by jsseng** [comment]
Can you have the code produce the inference images as well (for model0.pt for example)?  I wanted to figure out what the predictions looked like.

**Comment by jsseng** [comment]
Could you make the .csv already sorted in ascending order by variance?
