### ISSUE TITLE
add command line option to specify where to download data

### ISSUE THREAD

**Issue by jsseng** [htrick/Senior-Project#4]
add a command line option to get:  only labelbox data, only scale.ai data, or use both

**Comment by htrick** [comment]
Since each file is an export from either LabelBox or scale.ai, won't all images downloaded from a file be from the same place? Do you mean split up the downloads into separate folders for LabelBox and scale.ai images, or am I misunderstanding the task?

**Comment by jsseng** [comment]
It would be nice to have a command line flag to just download LabelBox data vs. scale.ai data.  They could be placed in the same directory.  Something like:

extractor -labelbox file.csv    or
extractor -scale scale.json    or
extractor -labelbox file.csv -scale scale.json

Something to that effect.
